name: FTP Deploy

on:
  push:
    branches:
      - main  # Acionado sempre que houver um push na branch principal

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer o checkout do código do repositório
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Baixa todo o histórico do repositório para evitar problemas de commits

      # Passo 2: Deploy via FTP
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # Diretório local do repositório
          server-dir: /public_html/  # Diretório remoto no servidor
          log-level: verbose  # Logs detalhados para debug
